dist: xenial
language: python
python:
  - "3.7"
cache: pip
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - export JIRAONEUSERNAME
  - export JIRAONEUSERPASS
  - export JIRAONEUSERURL
  - python test.py
